Algoritmo "TipoHelloWorld"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/03/2022
Var
// Seção de Declarações das variáveis 
aluno: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("digite um nome")
leia(aluno)
aluno <- "Lara"
escreval(aluno)

Fimalgoritmo